#I have reconstructed this based on the architecture requirements: it sets up the VPC, the vulnerable EC2 instance running OWASP Juice Shop, the private S3 bucket, and the necessary IAM roles that allow the specific "IMDS Credential Theft" attack path to work.

#I have reconstructed this based on the architecture requirements: it sets up the VPC, the vulnerable EC2 instance running OWASP Juice Shop, the private S3 bucket, and the necessary IAM roles that allow the specific "IMDS Credential Theft" attack path to work.

AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Threat Detection Lab: Deploys OWASP Juice Shop on EC2 with a private S3 bucket and GuardDuty enabled.'

Parameters:
  InstanceType:
    Description: EC2 Instance type (t2.micro is Free Tier eligible)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro

Resources:
  # -------------------------------------------------------------------------
  # Network Infrastructure (VPC, Subnet, IGW)
  # -------------------------------------------------------------------------
  LabVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: GuardDuty-Lab-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref LabVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  # -------------------------------------------------------------------------
  # Security (Security Group, IAM, GuardDuty)
  # -------------------------------------------------------------------------
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: !Ref LabVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # The Vulnerable IAM Role
  VulnerableRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${SecureDataBucket}"
                  - !Sub "arn:aws:s3:::${SecureDataBucket}/*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref VulnerableRole

  # -------------------------------------------------------------------------
  # Compute (The Vulnerable Web App)
  # -------------------------------------------------------------------------
  JuiceShopInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 (example)
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          docker run -d -p 80:3000 --restart always bkimminich/juice-shop
          echo "Dang it - if you can see this text, you're accessing our private information!" > secret-information.txt
          aws s3 cp secret-information.txt s3://${SecureDataBucket}/

  # -------------------------------------------------------------------------
  # Storage
  # -------------------------------------------------------------------------
  SecureDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  JuiceShopURL:
    Description: The URL of the vulnerable web application
    Value: !Sub "http://${JuiceShopInstance.PublicIp}"
  
  TheSecureBucket:
    Description: The name of the private S3 bucket containing the secret data
    Value: !Ref SecureDataBucket
